[versions]
agp = "8.5.0"
commonsValidator = "1.9.0"
converterJackson = "2.11.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"
service = "0.18.2"
preference = "1.2.1"

[libraries]
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "converterJackson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
service = { module = "com.theokanning.openai-gpt3-java:service", version.ref = "service" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

